image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

test:
    script:
        - cd docs
        - hugo
    except:
        - master

pages:
    script:
        - cd docs
        - hugo --verbose --verboseLog --destination ../public --baseURL https://gallegosj89.gitlab.io/webapps/
    artifacts:
        paths:
            - public
    only:
        - master
